M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu22.04.1} date 2026-01-06T15:49:16-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-06T15:49:16-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X84.0Y-49.0
X84.0Y-129.0
X174.0Y-49.0
X174.0Y-129.0
M30
