M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu22.04.1} date 2026-01-07T10:26:51-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-07T10:26:51-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X84.0Y-51.5
X84.0Y-116.5
X174.0Y-51.5
X174.0Y-116.5
M30
